### ISSUE TITLE
Maybe a better way to use FormValidation.io together with React/Preact. 

### ISSUE THREAD

**Issue by digitaldesigndj** [form-validation/examples#37]
`https://github.com/form-validation/examples/blob/master/react/DemoForm.js`

I see the example and I think it should make use of `refs`. React can pass a ref of the form to formvalidation.io instead of reaching for `document.getElementByID()`

Here's an example. This is `deno` code so JSX is baked in. (It's actually a [Fresh](http://fresh.deno.dev) island, so it's isomorphic too.) This is also functional style. I don't extend classes often, but the same idea works with hooks or classes.

```node
/** @jsx h */
import { Fragment, h } from "preact";
import { useEffect, useRef, useState } from "preact/hooks";

export default function LoginForm(props) {
  const [buttonDisabled, setButtonDisabled] = useState(false);
  const form = useRef(null);
  useEffect(() => {
    const fv = FormValidation.formValidation(
      form.current,
      {
        fields: {
          identifier: {
            validators: {
              notEmpty: {
                message: "Please provide an email address",
              },
              emailAddress: {
                message: "The value is not a valid email address",
              },
            },
          },
          password: {
            validators: {
              notEmpty: {
                message: "Please provide a password",
              },
              stringLength: {
                min: 6,
                message: "Passwords are at least 6 characters long",
              },
            },
          },
        },
        plugins: {
          trigger: new FormValidation.plugins.Trigger(),
          submitButton: new FormValidation.plugins.SubmitButton(),
          defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
          bootstrap5: new FormValidation.plugins.Bootstrap5({
            rowSelector: ".form-row",
          }),
        },
      },
    );
    fv.on("core.form.valid", () => {
      setButtonDisabled(true);
    });
  });
  return (
    <form ref={form} id="loginForm" method="POST" action="/signin">
      <div class="form-group">
        <label class="col-form-label">Username</label>
        <div class="form-row">
          <input type="text" class="form-control" name="identifier" />
        </div>
      </div>
      <div class="form-group">
        <label class="col-form-label">Password</label>
        <div class="form-row">
          <input type="password" class="form-control" name="password" />
        </div>
      </div>
      <div class="form-group my-3 d-grid gap-2">
        <button
          type="submit"
          class={`btn btn-dark ${buttonDisabled ? "disabled" : ""}`}
        >
          {buttonDisabled ? "Working..." : "Agent Login"}
        </button>
      </div>
    </form>
  );
}
```

I think this example could help some people so I wanted to float it your way.

This leads me to my real request. I would like to see a version of formvalidation.io that I can load as a JS module in the browser! This means es6, but with file suffixes. In the example above, I use FormValidation.io globally. I would like to include it like this:

three.js example
```node
/** @jsx h */
import { h } from "preact";
import { useEffect, useRef, useState } from "preact/hooks";

import * as THREE from "https://static.andbounds.com/three.js/three.module.js";
import { PLYLoader } from "https://static.andbounds.com/three.js/jsm/loaders/PLYLoader.js";
import { OrbitControls } from "https://static.andbounds.com/three.js/jsm/controls/OrbitControls.js";

export default function ScanViewer(props) {
  const { scan } = props;
  const element = useRef(null);
  const [loaded, setLoaded] = useState(false);
  // console.log( scan )

  useEffect(() => {
    element.current.style.height = element.current.clientWidth * 0.5625;
    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(
      35,
      element.current.clientWidth / element.current.clientHeight,
      0.1,
      10000,
    );

// lots of missing code
```

Thanks for the great code. 😃

**Comment by digitaldesigndj** [comment]
Here's an example repo: https://github.com/Hyprtxt/formvalidation.deno.dev and website https://formvalidation.deno.dev

**Comment by phuocng** [comment]
@digitaldesigndj 
Thanks for reaching out. The FormValidation library provides ES6 packages (located in the `dist/es6` folder), and you can import them instead of using them as the global.

I don't have experience with Deno, but here are some examples that might be useful to you
- https://formvalidation.io/guide/examples/bundling-with-webpack/
- https://formvalidation.io/guide/examples/bundling-with-rollup/

I'll take a look at how to integrate with Deno soon.

**Comment by digitaldesigndj** [comment]
So if you just use the browser to load a module "es6 style" with imports and the like, it requires the extension on the path. Deno behaves just like the browsers do. The idea here is that I can import the code without using a build step at all. So its like "Browser Native" JavaScript modules. Deno follows those same API's. I could make up an example with an `index.html`

In my example, I didn't include the import map. Check out how esm.sh works, since formvalidation isn't on npm its not there, but it's doing the thing I want FormValidation.io to do.

https://esm.sh/preact@10.10.0

`import_map.json`
```json
{
  "imports": {
    "$fresh/": "https://deno.land/x/fresh@1.0.2/",
    "preact": "https://esm.sh/preact@10.10.0",
    "preact/": "https://esm.sh/preact@10.10.0/",
    "preact-render-to-string": "https://esm.sh/preact-render-to-string@5.2.1?external=preact"
  }
}
```
