### ISSUE TITLE
startEndDate with a min value

### ISSUE THREAD

**Issue by mmc501** [form-validation/examples#38]
Hi, purchased and using the plugin - is it possible to have a min date with the startEndDate plugin.
It is adding a date for an event, but it is to prevent the user from entering a date in the past for the Start Date

**Comment by phuocng** [comment]
@mmc501 The `startEndDate` plugin doesn't have a minimum date option. However, you can use with a date picker library that provides a similar option.

For example, this [example](https://formvalidation.io/guide/examples/using-flatpickr-for-start-and-end-dates/) uses the flatpickr library which has a [`minDate` option](https://flatpickr.js.org/options/).
