### ISSUE TITLE
cloudflare turnstile

### ISSUE THREAD

**Issue by hassanbouaakab** [form-validation/examples#46]
Is there a way to integrate Turnstile Cloudflare’s smart CAPTCHA with form-validation. Thank you.

**Comment by phuocng** [comment]
@hassanbouaakab Thank you a lot for the question.
I think of creating a plugin for this instead of an example. I create this [issue](https://github.com/form-validation/form-validation/issues/112) to track the request.

**Comment by phuocng** [comment]
@hassanbouaakab Check the new Turnstile plugin in v2.4.0:
https://formvalidation.io/guide/plugins/turnstile/

**Comment by hassanbouaakab** [comment]
Thank you for your efforts.
